import type { Nutrient, NutrientId } from "./types";

/**
 * The nutrient registry, ordered the way the report reads.
 *
 * Tiers come from the evidence review, and several run against what a generic
 * nutrition app would say. Sodium is not an excess risk on a ketogenic diet —
 * low insulin drives natriuresis, so the real failure mode is too little.
 * Zinc, B12, B3 and B6 are never short here and are shown as wins. Iron flips
 * direction by sex and age. Fibre is absent from this list entirely: it is not
 * an essential nutrient, it has no EAR or RDA, and flagging it red would be the
 * fastest way to lose an audience that has already been told to eat kale.
 */
export const NUTRIENTS: Nutrient[] = [
  {
    id: "vitaminC",
    label: "Vitamin C",
    unit: "mg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "low",
    why: "Muscle meat carries almost none, and cooking destroys what little there is. Chicken liver and spleen are the only meaningful animal sources — beef liver is not one, at 1.9mg per 100g.",
  },
  {
    id: "vitaminK2",
    label: "Vitamin K2 (MK-4)",
    unit: "mcg",
    tier: "gap",
    evidenceGap: "medium",
    evidenceHarm: "low",
    why: "The animal form, concentrated in egg yolk, butter, chicken fat and organs. A lean muscle-only diet gets close to none. Tracked separately from K1, which behaves differently.",
  },
  {
    id: "vitaminK1",
    label: "Vitamin K1",
    unit: "mcg",
    tier: "conditional",
    evidenceGap: "high",
    evidenceHarm: "low",
    why: "Comes from green leaves, so intake is near zero by definition. Hepatic recycling and gut synthesis make frank clotting problems rare.",
  },
  {
    id: "calcium",
    label: "Calcium",
    unit: "mg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "low",
    why: "Calcium lives in bone, milk and plants — not in muscle. A kilo of beef supplies about 150mg, 15% of the day. Serum calcium stays normal because PTH strips bone to hold it there, so a blood test will not show this.",
  },
  {
    id: "magnesium",
    label: "Magnesium",
    unit: "mg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "medium",
    why: "Short on both ends: meat carries only ~20mg per 100g, and ketogenic natriuresis increases urinary losses. This is the deficiency people actually feel — cramps, palpitations, broken sleep.",
  },
  {
    id: "manganese",
    label: "Manganese",
    unit: "mg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "low",
    why: "Distributed almost entirely in plants; meat has effectively none. The numeric shortfall is dramatic, but spontaneous dietary deficiency has never been well characterised in adults. Mussels are the one animal food that fixes it.",
  },
  {
    id: "sodium",
    label: "Sodium",
    unit: "mg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "high",
    why: "The alert runs backwards here. Low insulin removes its antinatriuretic effect on the kidney, so sodium is dumped. Under-salting is the single most common cause of fatigue, cramps, headache and dizziness in the first month.",
  },
  {
    id: "potassium",
    label: "Potassium",
    unit: "mg",
    tier: "gap",
    evidenceGap: "medium",
    evidenceHarm: "medium",
    why: "Beef is a decent source at ~300mg per 100g, so a kilo roughly reaches the AI — but few people eat a kilo. Kaliuresis follows the sodium loss, so the target sits above the standard AI, not below.",
  },
  {
    id: "vitaminD",
    label: "Vitamin D",
    unit: "IU",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "medium",
    why: "No land animal food carries a useful amount. Fatty fish and sunlight are the real sources, which makes this the one nutrient your latitude and season decide more than your plate.",
  },
  {
    id: "folate",
    label: "Folate",
    unit: "mcg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "medium",
    why: "Muscle carries 5–12mcg per 100g. Liver carries 250–580. This is a gap that closes completely with organs once a week or eggs daily, and stays wide open without them.",
  },
  {
    id: "b1",
    label: "Thiamin (B1)",
    unit: "mg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "medium",
    why: "Beef is a poor source — a whole kilo gives about half a day's worth — and thiamin is heat-labile and water-soluble, so long cooking and discarded juices cost more. Pork is the exception that fixes it.",
  },
  {
    id: "vitaminE",
    label: "Vitamin E",
    unit: "mg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "low",
    why: "Comes from seed oils and nuts, so intake is near zero. The requirement scales with polyunsaturated fat intake — on ruminant fat the real need is far below the RDA, but a bacon-and-chicken diet keeps the need high while intake stays at zero.",
  },
  {
    id: "iodine",
    label: "Iodine",
    unit: "mcg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "medium",
    why: "Almost entirely decided by which salt is in the shaker. Swapping table salt for pink or sea salt removes the only reliable source without replacing it — and pink salt carries under 0.1mcg per gram.",
  },
  {
    id: "epaDha",
    label: "Omega-3 (EPA+DHA)",
    unit: "mg",
    tier: "gap",
    evidenceGap: "high",
    evidenceHarm: "medium",
    why: "Land animals supply essentially none. Only fatty fish, roe and some shellfish carry EPA and DHA in useful amounts.",
  },
  {
    id: "copper",
    label: "Copper",
    unit: "mg",
    tier: "conditional",
    evidenceGap: "medium",
    evidenceHarm: "medium",
    why: "Muscle is poor in copper and rich in zinc, and zinc induces the intestinal protein that sequesters copper and sends it out in stool. Liver or oysters fix it outright; without them the ratio drifts badly.",
  },
  {
    id: "choline",
    label: "Choline",
    unit: "mg",
    tier: "conditional",
    evidenceGap: "medium",
    evidenceHarm: "medium",
    why: "Usually fine — a kilo of beef nearly covers it and eggs or organs put it well over. The exception is a lower-calorie diet with no eggs and no organs.",
  },
  {
    id: "biotin",
    label: "Biotin",
    unit: "mcg",
    tier: "conditional",
    evidenceGap: "low",
    evidenceHarm: "low",
    why: "Not a carnivore gap. The one real risk is raw egg white, whose avidin binds biotin irreversibly — cooking denatures it and the problem disappears.",
  },
  {
    id: "selenium",
    label: "Selenium",
    unit: "mcg",
    tier: "strength",
    evidenceGap: "low",
    evidenceHarm: "low",
    why: "Comfortably covered by meat, and covered several times over by kidney or seafood.",
  },
  {
    id: "b12",
    label: "Vitamin B12",
    unit: "mcg",
    tier: "strength",
    evidenceGap: "low",
    evidenceHarm: "low",
    why: "Carnivore delivers five to twenty times the RDA. This is never the problem.",
  },
  {
    id: "b2",
    label: "Riboflavin (B2)",
    unit: "mg",
    tier: "strength",
    evidenceGap: "low",
    evidenceHarm: "low",
    why: "Met or exceeded in every modelled carnivore diet. Heat-stable, unlike thiamin.",
  },
  {
    id: "b3",
    label: "Niacin (B3)",
    unit: "mg",
    tier: "strength",
    evidenceGap: "low",
    evidenceHarm: "low",
    why: "Abundant in all muscle meat.",
  },
  {
    id: "b5",
    label: "Pantothenic acid (B5)",
    unit: "mg",
    tier: "strength",
    evidenceGap: "low",
    evidenceHarm: "low",
    why: "Adequate from meat; liver supplies several days' worth in one serving.",
  },
  {
    id: "b6",
    label: "Vitamin B6",
    unit: "mg",
    tier: "strength",
    evidenceGap: "low",
    evidenceHarm: "low",
    why: "Adequate across every modelled carnivore diet.",
  },
  {
    id: "phosphorus",
    label: "Phosphorus",
    unit: "mg",
    tier: "strength",
    evidenceGap: "low",
    evidenceHarm: "low",
    why: "Far above requirement — which is precisely why the calcium-to-phosphorus ratio is worth watching.",
  },
  {
    id: "vitaminA",
    label: "Vitamin A (retinol)",
    unit: "mcg",
    tier: "excess",
    evidenceGap: "high",
    evidenceHarm: "high",
    why: "Not a deficiency here — a ceiling. 100g of cooked beef liver carries about 9,400mcg RAE, over three times the daily upper limit for preformed retinol.",
  },
  {
    id: "iron",
    label: "Iron",
    unit: "mg",
    tier: "excess",
    evidenceGap: "high",
    evidenceHarm: "high",
    why: "Direction depends on who you are. Menstruating women can fall short; everyone else accumulates, because heme iron is absorbed efficiently and the body has no active route to excrete it.",
  },
  {
    id: "zinc",
    label: "Zinc",
    unit: "mg",
    tier: "excess",
    evidenceGap: "high",
    evidenceHarm: "medium",
    why: "A kilo of beef delivers 50–60mg against an upper limit of 40, with no phytates to blunt absorption. The problem it causes is copper, not zinc itself.",
  },
];

export const NUTRIENT_BY_ID: Record<NutrientId, Nutrient> = Object.fromEntries(
  NUTRIENTS.map((n) => [n.id, n]),
) as Record<NutrientId, Nutrient>;
