/**
 * Symptoms that end the analysis instead of feeding it.
 *
 * This layer is hard-coded and rendered by TypeScript. It is never generated by
 * the model and never softened by it: if someone reports chest pain, the correct
 * output is "stop and get seen", not a magnesium suggestion with a caveat.
 */
export interface RedFlag {
  id: string;
  label: string;
  urgency: "emergency" | "urgent";
  reason: string;
}

export const RED_FLAGS: RedFlag[] = [
  { id: "chest-pain", label: "Chest pain, pressure or tightness", urgency: "emergency", reason: "This is never an electrolyte problem. Acute coronary syndrome has to be excluded first." },
  { id: "fainting", label: "Fainting or losing consciousness", urgency: "emergency", reason: "Syncope points at an arrhythmia or severe volume depletion, not at diet composition." },
  { id: "persistent-arrhythmia", label: "Persistent irregular heartbeat with breathlessness or dizziness", urgency: "emergency", reason: "A severe electrolyte disturbance or an underlying cardiac problem. Occasional skipped beats that resolve with electrolytes are different from this." },
  { id: "breathless-vomiting", label: "Breathless at rest, with persistent vomiting or confusion", urgency: "emergency", reason: "Possible ketoacidosis. It is rare in people without diabetes but documented, especially while breastfeeding or on an SGLT2 inhibitor, and it can occur with normal blood sugar." },
  { id: "confusion-seizure", label: "Confusion, disorientation or a seizure", urgency: "emergency", reason: "Severe hyponatraemia, hypoglycaemia or ketoacidosis." },
  { id: "blood-in-stool", label: "Blood in stool, black tarry stool, or vomiting blood", urgency: "emergency", reason: "Gastrointestinal bleeding." },
  { id: "severe-abdominal-pain", label: "Severe, persistent abdominal pain radiating to the back", urgency: "emergency", reason: "Pancreatitis or acute gallbladder disease." },
  { id: "jaundice", label: "Yellowing of skin or eyes", urgency: "emergency", reason: "Liver or biliary compromise." },
  { id: "kidney-stone-pain", label: "Severe flank pain in waves, or blood in urine", urgency: "urgent", reason: "Likely a kidney stone. Carnivore raises urinary calcium and uric acid while lowering citrate, so this needs imaging, not dietary tinkering." },
  { id: "hot-swollen-joint", label: "One hot, red, swollen, very painful joint", urgency: "urgent", reason: "Probable gout. Induction is exactly when it flares, because ketones and urate compete for the same renal transporter." },
  { id: "numbness-weakness", label: "Progressive numbness, tingling or weakness", urgency: "urgent", reason: "Possible B12 or copper-related neuropathy, which can become irreversible." },
  { id: "amenorrhea-3m", label: "No period for more than three months", urgency: "urgent", reason: "Sustained low energy availability. This needs assessment rather than another dietary adjustment." },
];

export const RED_FLAG_BY_ID: Record<string, RedFlag> = Object.fromEntries(
  RED_FLAGS.map((f) => [f.id, f]),
);
